// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Library_Page
{
    public partial class MyMachineLearning
    {
        /// <summary>
        /// model input class for MyMachineLearning.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"CustomerID")]
            public float CustomerID { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Genre")]
            public string Genre { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Age")]
            public float Age { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Annual Income (k$)")]
            public float Annual_Income__k__ { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Spending Score (1-100)")]
            public float Spending_Score__1_100_ { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MyMachineLearning.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"CustomerID")]
            public float CustomerID { get; set; }

            [ColumnName(@"Genre")]
            public string Genre { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Annual Income (k$)")]
            public float Annual_Income__k__ { get; set; }

            [ColumnName(@"Spending Score (1-100)")]
            public float Spending_Score__1_100_ { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("myMachineLearning.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
